---
title: "herbivory"
author: "Ewout Knoester"
Date: "11 May 2021"
output: html_document
---

# Set R and packages
```{r setup}
rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks

library(plyr) # Join data frames (vlookup)
library(tidyverse) # Data manipulation and plotting
library(ggthemes) # Pretty plots
library(betareg) # Beta regression
library(glmmTMB) # Nested beta regression
library(DHARMa) # Nested model validation
library(emmeans) # Pairwise comparisons
library(multcompView) # Significance letters to plots
library(car) # ANOVA results GLM
library(NCmisc) # Check packages used

# Function to facilitate averaging data frame
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x)))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- plyr::rename(data_sum, c("mean" = varname))
 return(data_sum)
}
```

# Load & organize data
<!--
Data info:
  Data collected by Veerle Plug
  Grazing (%) on macrophyte calculated as: Weight(out)/(Weight(in)*(1-Weight_control))
  Weight = wet weight of macrophyte (shaken 10 times)
  Weight_control = biomass loss on caged structures, calculated for each location x macrophyte combination.
  Weight_control on average 19%
  Weight_control was 1 of the 11 structures, randomly chosen. Raw data not included in this data set
  After correction with Weight_control, grazing > 100 was set to 100 and grazing < 0 was set to 0
  ~1 day interval between measurement Weight(out) and Weight(in), standardized to 24hrs exactly
-->
```{r data loading}
# Load data and assign factors
Assays <- read.csv("Macrophyte buffet assays_Herbivory browsing.csv", 
 colClasses = c(ID = "factor", Assay = "factor", Structure = "factor", Location = "factor", Date = "factor", Species = "factor"))

# Insert new columns for Protection and fill based on study site
Assays$Protection <- as.factor(ifelse(Assays$Location %in% c("Firefly", "Pilli Pipa"), "Fished",
                     ifelse(Assays$Location %in% c("Dolphin Point", "Lower Mpunguti"), "Reserve",
                                                   "No-take")))


# Change Location names to numbers
Assays$Location <- ifelse(Assays$Location %in% c("Firefly"),"1",
                   ifelse(Assays$Location %in% c("Pilli Pipa"),"2",
                   ifelse(Assays$Location %in% c("Lower Mpunguti"),"3",
                   ifelse(Assays$Location %in% c("Dolphin Point"),"4",
                   ifelse(Assays$Location %in% c("Kisite"), "5", "6")))))
Assays$Location <- factor(Assays$Location)

# Transform percentages to fractions
Assays <- as.data.frame(append(Assays,list(Grazing.fraction = Assays$Grazing/100),after = 9))

# Averaging values across assay structures
Assays.avg <- ddply(Assays, ~Assay+Species, summarise, Grazing.mean = mean(Grazing.fraction), 
                    Protection = Protection[1], Location = Location[1])

# Transform data, because Beta regression doesn't accept 0s and 1s
transform01 <- function(x) {
  (x * (length(x) - 1) + 0.5) / (length(x))
}
Assays.avg$Grazing.scaled <- transform01(Assays.avg$Grazing.mean)

```

# Data inspection
```{r data inspection}
summary(Assays) # Check data: no missing data (NAs)

# Histograms to check for distributions raw data: Averaging per survey clearly improves distribution
hist(Assays$Grazing)
hist(Assays.avg$Grazing.mean)

# Boxplots of Grazing split per Protection, Location and Species
boxplot(Grazing.mean ~ Protection, varwidth = TRUE, data = Assays.avg)
boxplot(Grazing.mean ~ Location, varwidth = TRUE, data = Assays.avg)
boxplot(Grazing.mean ~ Species, varwidth = TRUE, data = Assays.avg)

# Plotting Grazing across Assay nested within Location and Protection
ggplot() +
  geom_point(aes(x = Assay, y = Grazing.mean, color = Species), data = Assays.avg) +
  facet_grid(. ~ Protection + Location, switch = "x") +
  scale_color_manual(values=c("#999999", "#666666", "#323232"))+
  theme(
    axis.text.x = element_text(size = 11), axis.text.y = element_text(size = 11),
    axis.title.x = element_text(size = 11), axis.title.y = element_text(size = 11),
    panel.background = element_rect(fill = "white", colour = NA),
    panel.border = element_rect(fill = NA, colour = "grey50"),
    panel.grid.major = element_line(colour = "grey90", size = 0.2),
    panel.grid.minor = element_line(colour = "grey98", size = 0.5),
    strip.background = element_rect(fill = "grey80", colour = "grey50"),
    legend.text = element_text(size = 11), strip.text.x = element_text(size = 11)
  ) +
  ylab("Grazing (%)") + xlab("Survey")
```

# Pooled*Nested model (Protection)
<!--
Data observations:
  Data bounded between 0 and 100: not suited for normal linear models;
  Pooled model (archive) invalid because of independency;
  Full nested model (Location/Assay) could not be fitted properly (archive)
  A pooling across Assays (i.e. average of 10 lines) was used for analysis, and this was nested within Location
-->
## Pooled*Nested model (Protection) selection
```{r pooled*nested model (protection) selection}

# --- PROTECTION ---

## Data prep: add depth as covariate
Assays.avg$Depth <- ifelse(Assays.avg$Location == 1, 2.4,
                    ifelse(Assays.avg$Location == 2, 5.5,
                    ifelse(Assays.avg$Location == 3, 4.7,
                    ifelse(Assays.avg$Location == 4, 8.4,
                    ifelse(Assays.avg$Location == 5, 10.2,
                    ifelse(Assays.avg$Location == 6, 3.2, 99))))))

## Add ReefType as covariate
Assays.avg$ReefType <- ifelse(as.numeric(Assays.avg$Location) < 3, "Patch", ifelse(as.numeric(Assays.avg$Location) > 5, "Patch", "Fringe"))
                           
# Null model
glm.null <- glmmTMB(Grazing.scaled ~ 1, data = Assays.avg, family = list(family = "beta", link = "logit"))

# Incorporating nested structure (use REML to compare using AIC)
glm.1 <- glmmTMB(Grazing.scaled ~ Protection*Species, data = Assays.avg, 
                 family = list(family = "beta", link = "logit"), REML = TRUE)
glm.1a <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), REML = TRUE)
glm.1b <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), REML = TRUE)

AIC(glm.1, glm.1a, glm.1b) # Full nested structure (glm.1b) best model and deals with independence of Location within Protection and Species within Assay

# Allowing for variable precision (dispersion) using full nested model
glm.2a <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Location)
glm.2b <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Species)
glm.2c <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Protection)
glm.2d <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Location+Species)
glm.2e <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Species+Protection)
glm.2f <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Location+Protection)

AIC(glm.1b, glm.2a, glm.2b, glm.2c, glm.2d, glm.2e, glm.2f) # Species + Protection (glm.2e) best fit (without convergence problems)

# Final model for pooled*nested data, including interaction and variable precision:
## Including ReefType didn't change AIC (dif < 0.1) thus left out of final model
glm.3 <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Species+Protection)

summary(glm.3)
car::Anova(glm.3)

# --- LOCATION ---
glm.3loc <- glmmTMB(Grazing.scaled ~ Location*Species + (1 | Assay), data = Assays.avg, 
                  family = list(family = "beta", link = "logit"), dispformula = ~ Species+Protection)

car::Anova(glm.3loc)

```

## Pooled*Nested (Protection) model validation
```{r pooled*nested (protection) model validation}

# --- PROTECTION ---
mod <- glm.3
modOutput <- simulateResiduals(fittedModel = mod, plot = F)

op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2))
plotResiduals(modOutput, quantreg = T, quantiles = 0.5, rank = T, smoothScatter = F)
testDispersion(modOutput)
testUniformity(modOutput)
plotResiduals(modOutput, form = Assays.avg$Protection)
plotResiduals(modOutput, form = Assays.avg$Species)
abline(0,0)
plot(fitted(mod) ~ Assays.avg$Grazing.scaled)
par(op)

# --- LOCATION ---
mod <- glm.3loc
modOutput <- simulateResiduals(fittedModel = mod, plot = F)

op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2))
plotResiduals(modOutput, quantreg = T, quantiles = 0.5, rank = T, smoothScatter = F)
testDispersion(modOutput)
testUniformity(modOutput)
plotResiduals(modOutput, form = Assays.avg$Protection)
plotResiduals(modOutput, form = Assays.avg$Species)
abline(0,0)
plot(fitted(mod) ~ Assays.avg$Grazing.scaled)
par(op)

```

## Pooled*Nested model (Protection) Post hoc
```{r pooled*nested model (protection) post hoc}
# PROTECTION
HSD.PNps <- emmeans(glm.3, specs = pairwise ~ Protection|Species, adjust = "tukey", type = "response")

# LOCATION
HSD.loc <- emmeans(glm.3loc, specs = pairwise ~ Location|Species, adjust = "tukey", type = "response")

```

## Pooled*Nested model (Protection) plotting
```{r pooled*nested model (protection) plotting}

### --- PROTECTION ---
## SARGASSUM & PADINA
# Get averages protection
summaryx <- data_summary(Assays.avg, varname = "Grazing.scaled", groupnames = c("Protection", "Species"))
summaryx <- subset(summaryx, Species == "Sargassum" | Species == "Padina")

# Set ordering of factors
summaryx$Protection <- ordered(summaryx$Protection, levels = c("Fished", "Reserve", "No-take"))
summaryx$Species <- ordered(summaryx$Species, levels = c("Sargassum", "Padina", "Thalassia"))

# Post hoc letters
sigletters.loc <- multcomp::cld(HSD.PNps$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD
sigletters.loc <- subset(sigletters.loc, Species == "Sargassum" | Species == "Padina")

# Make order match with summary dataframe
sigletters.loc <- sigletters.loc[order(sigletters.loc$Protection),]
sigletters.loc <- sigletters.loc %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
summaryx <- cbind(summaryx, siglet.loc = sigletters.loc$.group)

# Plot Protection for Both
ggplot(summaryx, aes(x = Protection, fill = Protection, y = Grazing.scaled))+
  geom_bar(stat = "identity", position = position_dodge())+ 
   facet_grid(~Species) +
  labs(x = "Fisheries management")+
  scale_y_continuous( "Macroalgae consumed (F)", breaks = c(0, 0.5,1), label = waiver (), limits = c (0,1.05))+
  geom_errorbar(aes(ymin=Grazing.scaled-(1*se), ymax=Grazing.scaled+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = summaryx, aes(x=Protection, y = Grazing.scaled + se, label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_fill_manual(values=c("#999999", "#666666", "#323232"))+
  theme_economist()+scale_colour_economist()+
  theme(
    legend.position = "none",
    panel.spacing = unit(0, "lines"), 
    axis.title.x = element_text(color="black", vjust=-4, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=5, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    strip.text.x = element_text(size = 14, face = "bold.italic", vjust = 3, margin = margin(t = 10, b = 0)),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3)
    ) 
ggsave("Herbivory_Grazing Both (Protection).tiff", width = 23, height = 11, units = "cm", dpi=1200, compression = "lzw")

## Thalassia

# Get averages protection
summaryxT <- data_summary(Assays.avg, varname = "Grazing.scaled", groupnames = c("Protection", "Species"))
summaryxT <- subset(summaryxT, Species == "Thalassia")

# Set ordering of factors
summaryxT$Protection <- ordered(summaryxT$Protection, levels = c("Fished", "Reserve", "No-take"))
summaryxT$Species <- ordered(summaryxT$Species, levels = c("Sargassum", "Padina", "Thalassia"))


# Post hoc letters
sigletters.loc <- multcomp::cld(HSD.PNps$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD
sigletters.loc <- subset(sigletters.loc, Species == "Thalassia")

# Make order match with summary dataframe
sigletters.loc <- sigletters.loc[order(sigletters.loc$Protection),]
sigletters.loc <- sigletters.loc %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
summaryxT <- cbind(summaryxT, siglet.loc = sigletters.loc$.group)

# Plot Protection for Thalassia
ggplot(summaryxT, aes(x = Protection, fill = Protection, y = Grazing.scaled))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(x = "Fisheries management")+
  scale_y_continuous( "Thalassia consumed (F)", breaks = c(0, 0.5,1), label = waiver (), limits = c (0,1.1))+
  geom_errorbar(aes(ymin=Grazing.scaled-(1*se), ymax=Grazing.scaled+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = summaryxT, aes(x=Protection, y = Grazing.scaled + (1*se), label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_fill_manual(values=c("#999999", "#666666", "#323232"))+
  theme_economist()+scale_colour_economist()+
  theme(
    legend.position = "none",
    panel.spacing = unit(0, "lines"), strip.background = element_blank(),  strip.placement = "outside",
    axis.title.x = element_text(color="black", vjust=-2, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=4, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3)
    ) 
ggsave("Herbivory_Grazing Thalassia (Protection).tiff", width = 23, height = 11, units = "cm", dpi=1200, compression = "lzw")

### --- LOCATION
## SARGASSUM & PADINA
# Get averages protection
summaryx.loc <- data_summary(Assays.avg, varname = "Grazing.scaled", groupnames = c("Protection ","Location", "Species"))
summaryx.loc <- subset(summaryx.loc, Species == "Sargassum" | Species == "Padina")

# Set ordering of factors
summaryx.loc$Protection <- ordered(summaryx.loc$Protection, levels = c("Fished", "Reserve", "No-take"))
summaryx.loc$Species <- ordered(summaryx.loc$Species, levels = c("Sargassum", "Padina", "Thalassia"))

# Post hoc letters
sigletters.locx <- multcomp::cld(HSD.loc$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD
sigletters.locx <- subset(sigletters.locx, Species == "Sargassum" | Species == "Padina")

# Make order match with summary dataframe
sigletters.locx <- sigletters.locx[order(sigletters.locx$Location),]
sigletters.locx <- sigletters.locx %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
summaryx.loc <- summaryx.loc[order(summaryx.loc$Location),]
summaryx.loc <- cbind(summaryx.loc, siglet.loc = sigletters.locx$.group)

# Plot Location for Both
ggplot(summaryx.loc, aes(x = Location, fill = Protection, y = Grazing.scaled))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  facet_grid(~Species) +
  labs(x = "Study site")+
  scale_y_continuous( "Macroalgae consumed (F)", breaks = c(0, 0.5,1), label = waiver (), limits = c (0,1.05))+
  geom_errorbar(aes(ymin=Grazing.scaled-(1*se), ymax=Grazing.scaled+(1*se)), width=.2, position=position_dodge(.9))+
  geom_text(data = summaryx.loc, aes(x=Location, y = Grazing.scaled + se, label = siglet.loc), 
            vjust= -0.8, hjust = 0.5, size = 5, fontface = "bold", position=position_dodge(.9))+
  scale_fill_manual(values=c("#999999", "#666666", "#323232"))+
  theme_economist()+scale_colour_economist()+
  theme(
    panel.spacing = unit(0, "lines"), 
    axis.title.x = element_text(color="black", vjust=-4, size = 14),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=5, size = 14),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.4),
    strip.text.x = element_text(size = 14, face = "bold.italic", vjust = 3, margin = margin(t = 10, b = 0)),
    plot.margin = margin(t = 10, r = 40,  b = 25,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3)
    ) 
ggsave("Herbivory_Grazing Both (Location).tiff", width = 23, height = 11, units = "cm", dpi=1200, compression = "lzw")

```

# Check packages used
```{r}

knitr::purl("herbivory.Rmd")
list.functions.in.file("herbivory.R")
unlink("herbivory.R")

```

