---
title: "herbivory model archive"
author: "Ewout Knoester"
Date: "12 August 2021"
output: html_document
---

# Pooled analysis Beta regression
<!--
The pooled analysis can't be used because it ignores the nested structure of the data (ie assumes independence where there isn't)
-->
## Pooled model selection
```{r pooled model selection}

# Classical ANOVA (assuming normally distributed errors)
#lm.ref <- lm(Grazing.scaled ~ Protection*Species, data = Assays.avg)

# Null model
bm.null <- betareg(Grazing.scaled ~ 1, data = Assays.avg)
summary(bm.null)

# Full model
bm.1 <- betareg(Grazing.scaled ~ Protection*Species, data = Assays.avg) 
summary(bm.1)

# Allowing for varying precision/variance using full model
bm.1a <- betareg(Grazing.scaled ~ Protection*Species | Location, data = Assays.avg) 
bm.1b <- betareg(Grazing.scaled ~ Protection*Species | Species, data = Assays.avg) 
bm.1c <- betareg(Grazing.scaled ~ Protection*Species | Protection, data = Assays.avg) 
bm.1d <- betareg(Grazing.scaled ~ Protection*Species | Location*Species, data = Assays.avg) 
bm.1e <- betareg(Grazing.scaled ~ Protection*Species | Protection*Species, data = Assays.avg)

AIC(bm.1, bm.1a, bm.1b, bm.1c, bm.1d, bm.1e) # Location & Location*Species showing greatest improvement precision
lrtest(bm.1a, bm.1d) # Location*Species significantly better than Location only, despite high Df

# Model selection
bm.2a <- betareg(Grazing.scaled ~ Protection | Location*Species, data = Assays.avg)
bm.2b <- betareg(Grazing.scaled ~ Species | Location*Species, data = Assays.avg) 
bm.2c <- betareg(Grazing.scaled ~ Protection*Species | Location*Species, data = Assays.avg)

AIC(bm.2a, bm.2b, bm.2c) # Full model (with interaction) best fit 

# Bias reduction
bm.3 <- betareg(Grazing.scaled ~ Protection*Species | Location*Species, data = Assays.avg)
bm.3bc <- betareg(Grazing.scaled ~ Protection*Species | Location*Species, data = Assays.avg, type = "BC")

AIC(bm.3, bm.3bc) # Bias reduction does not result in model improvement

# Final model for pooled data, including interaction and variable precision and without bias correction
summary(bm.3)
```
## Pooled model fit
```{r}

mod <- bm.3
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2))
plot(resid(mod) ~ fitted(mod))
abline(0,0)
plot(Assays.avg$Grazing.scaled, resid(mod))
abline(0,0)
hist(resid(mod), main = "")
qqnorm(resid(mod))
plot(Assays.avg$Protection, resid(mod))
abline(0,0)
plot(Assays.avg$Location, resid(mod))
abline(0,0)
plot(Assays.avg$Species, resid(mod))
abline(0,0)
plot(fitted(mod) ~ Assays.avg$Grazing.scaled)
par(op)
```
## Pooled Post hoc
```{r}
test(pairs(emmeans(bm.3, ~ Protection | Species, mode = "link")))
```

# Full nested model
<!--
The full nested analysis won't be used because didn't manage to get the residuals homogenous, resulting in weaker inferences
-->
## Full nested model selection
```{r nested model selection}

# Transform data, because Beta regression doesn't accept 0s and 1s
Assays$Grazing.scaled <- transform01(Assays$Grazing.fraction)

# Null model
glm.FNnull <- glmmTMB(Grazing.scaled ~ 1, data = Assays, family = list(family = "beta", link = "logit"))

# Full model
glm.FN1 <- glmmTMB(Grazing.scaled ~ Protection*Species, data = Assays, family = list(family = "beta", link = "logit"))

# Incorporating nested structure
glm.FN1a <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location), data = Assays, family = list(family = "beta", link = "logit"))
glm.FN1b <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Assay), data = Assays, family = list(family = "beta", link = "logit"))
glm.FN1c <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"))

AIC(glm.FN1, glm.FN1a, glm.FN1b, glm.FN1c) # Full nested structure (glm.FN1c) improves model performance

# Allowing for variable precision using full nested model
glm.FN2 <- glm.FN1c
glm.FN2a <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Location)
glm.FN2b <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Species)
glm.FN2c <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Protection)
glm.FN2d <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Location*Species)
glm.FN2e <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Species*Protection)

AIC(glm.FN2, glm.FN2a, glm.FN2b, glm.FN2c, glm.FN2d, glm.FN2e) # Location*Species (glm.FN2d) greatest improvement 
# Model selection
glm.FN3a <- glmmTMB(Grazing.scaled ~ Protection + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Location*Species)
glm.FN3b <- glmmTMB(Grazing.scaled ~ Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Location*Species)
glm.FN3c <- glmmTMB(Grazing.scaled ~ Protection+Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Location*Species)
glm.FN3d <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Location*Species)

AIC(glm.FN3a, glm.FN3b, glm.FN3c, glm.FN3d) # Full model (with interaction) best fit 

# Final model for nested data, including interaction and variable precision
glm.FN4 <- glmmTMB(Grazing.scaled ~ Protection*Species + (1 | Location/Assay), data = Assays, family = list(family = "beta", link = "logit"), dispformula = ~ Location*Species)
summary(glm.FN4)
```
## Full nested model validation
```{r}
# Dharma checks, see: https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html
mod <- glm.FN4
modOutput <- simulateResiduals(fittedModel = mod, plot = F)

op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2))
plotResiduals(modOutput, quantreg = T, quantiles = 0.5, rank = T, smoothScatter = F)
testDispersion(modOutput)
testUniformity(modOutput)
plotResiduals(modOutput, form = Assays$Protection)
plotResiduals(modOutput, form = Assays$Species)
abline(0,0)
plot(fitted(mod) ~ Assays$Grazing.scaled)
par(op)

plot(fitted(glm.FN4), resid(glm.FN4))
```
## Full nested Post hoc
```{r}
test(pairs(emmeans(glm.FN4, ~ Protection | Species, mode = "link")))
```