---
title: "RUV"
author: "Ewout Knoester"
date: "31/08/2021"
output: html_document
---

# Setup
```{r setup, include=FALSE}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks
options(scipen = 50) # Have all numbers in non-scientific notation

library(plyr) # Join (vlookup)
library(data.table) # Easy data frame handling
library(flextable) # layout table
library(officer) # Move table into word
library(writexl)
library(panelr)
library(tidyverse) # Data manipulation and plotting
library(ggthemes) # Pretty plots
library(readxl) # Import excel sheets
library(htmlTable) # Data table

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(sum = sum(x[[col]], na.rm=TRUE),
      mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]])))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  #data_sum <- plyr::rename(data_sum, c("mean" = varname))
 return(data_sum)
}

```

# Data selection (preparing dataset for archiving & sharing)
```{r prepare data}

# RAW data
## load first Excel sheet
df0.raw <- read_excel("Raw data/RUV bites_DATABASE_2022-08.xlsx", sheet = 3, skip = 1)

## combining next sheets of Excel file
for (i in 4:5) {
  temp <- read_excel("Raw data/RUV bites_DATABASE_2022-08.xlsx", sheet = i, skip = 1)
  df0.raw <- cbind(df0.raw, temp)
}

# Cleaning data
## Remove NA Species (= calculation cells Excel)
df1.clean <- df0.raw[!is.na(df0.raw$Species),]
df1.clean[is.na(df1.clean)] <- 0
df1.clean <- select(df1.clean, -c(1, 3:5, 2706:2710, 5411:5415))

## Convert to long dataframe
df1.clean <- as.data.frame(long_panel(df1.clean, prefix = "_", begin = 1, end = 300, label_location = "end"))

## Add Genus
df1.clean <- as.data.frame(append(df1.clean, list(Genus = word(df1.clean$Species, 1)), after = 3))

##Sort by survey
df1.clean <- df1.clean[order(df1.clean$wave),]
df1.clean$Species <- gsub("[[:punct:]]", "", df1.clean$Species) # Remove points from sp.

# GROUPING data (functional groups)
## Load Excel
fg <- read_excel("Raw data/SpeciesList_2022-08.xlsx", sheet = 1)
fg <- dplyr::select(fg, c('Species', 'Diet', 'DietH', 'a', 'b'))
fg$Species <- gsub("[[:punct:]]", "", fg$Species) # Remove points from sp.
fg$a <- as.numeric(fg$a)

# MERGE RAW and GROUPING
df1.clean <- left_join(df1.clean, fg, by="Species")

# META data
## Load Excel
meta <- read_excel("Raw data/RUV bites_DATABASE_2022-08.xlsx", sheet = 2)

## Cleaning META data
### Change location names to numbers
meta$Location <- as.factor(ifelse(meta$Location  == 'Firefly', 1,
                  ifelse(meta$Location  == 'Pilli Pipa', 2, 
                   ifelse(meta$Location  == 'Lower Mpunguti', 3, 
                    ifelse(meta$Location  == 'Dolphin Point', 4, 
                     ifelse(meta$Location  == 'Kisite', 5, 6))))))

### Set Protection per Location
meta$Protection <- as.factor(ifelse(meta$Location  == 1, "Fished",
                  ifelse(meta$Location  == 2, "Fished", 
                   ifelse(meta$Location  == 3, "Reserve", 
                    ifelse(meta$Location  == 4, "Reserve", 
                     ifelse(meta$Location  == 5, "No-take", "No-take"))))))

# Select relevant surveys (i.e. Observer = Veerle) from RAW data using criteria of META data
df2.selex <- df1.clean[df1.clean$wave %in% c(unlist(na.omit(meta$RUV[meta$Observer == "Veerle Plug"]))),]

# Merge RAW and META
meta <- dplyr::select(meta, c('RUV', 'Location', 'Protection', 'Duration.min')) # Select relevant META data
names(df2.selex)[2] <- "RUV" # Rename column so both data frames have now an RUV ID columns
df2.selex <- left_join(df2.selex, meta, by = "RUV") # Merge by RUV number

df2.selex <- select(df2.selex, -c("id", "TOT":"TOTg"))
df2.selex[is.na(df2.selex)] <- 0

# Wide to long for biomass calculations
df2.selex <- reshape2::melt(df2.selex, id.vars=c('RUV', 'Genus', 'Species', 'Diet', 'DietH',
                                                 'a', 'b', 'Location', 'Protection', 'Duration.min' ),                    measure.vars = c('X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12'),
             variable.name = 'SizeClass', value.name = 'Bites')

# Transform size classes back to numeric (mid size class)
df2.selex$SizeClass <- ifelse(df2.selex$SizeClass == "X1", 1.25,
                         ifelse(df2.selex$SizeClass == "X2", 3.75,
                         ifelse(df2.selex$SizeClass == "X3", 6.25,
                         ifelse(df2.selex$SizeClass == "X4", 8.75,
                         ifelse(df2.selex$SizeClass == "X5", 12.5,
                         ifelse(df2.selex$SizeClass == "X6", 17.5,
                         ifelse(df2.selex$SizeClass == "X7", 25,
                         ifelse(df2.selex$SizeClass == "X8", 35,
                         ifelse(df2.selex$SizeClass == "X9", 45,
                         ifelse(df2.selex$SizeClass == "X10", 75,
                         ifelse(df2.selex$SizeClass == "X11", 125,
                         ifelse(df2.selex$SizeClass == "X12", 175, 0))))))))))))

# Calculate mass-scaled bites per min
df2.selex$smsBites <- (((((df2.selex$a * (df2.selex$SizeClass ^ df2.selex$b)) * df2.selex$Bites))/ 45))

# Cleanup
df2.selex <- select(df2.selex, -c("a", "b", "Duration.min", "SizeClass", "Bites"))

# Meta to get species differences
meta <- read_excel("Raw data/RUV bites_DATABASE_2022-08.xlsx", sheet = 2)
meta$Comments[is.na(meta$Comments)] <- ""

# Also perform selection on meta
meta <- meta[str_detect(meta$Observer, "Veerle Plug"),]
meta <- meta[!str_detect(meta$Object, "Thalassia"),]
meta <- select(meta, c('RUV', 'Object')) # Relevant meta
df2.selex <- left_join(df2.selex, meta, by = "RUV")
df2.selex <- df2.selex %>% drop_na(c("Object")) # Drop Thalassia

# Sum over all size classes
df2.selex <- data_summary(df2.selex, varname = "smsBites",
                        groupnames = c("RUV","Genus", "Species", "Location", "Object"))
df2.selex <- select(df2.selex, -c("mean":"se"))
colnames(df2.selex)[which(names(df2.selex) == "sum")] <- "smsBites"

# EXPORT DATA SELECTION
write_xlsx(df2.selex,"RUV bites_Herbivory browsing.xlsx")

```

<!--
Data info:
  Data collected by Veerle Plug
  Data quantified by Veerle (then to be checked by Mercy & Cindy)
  Bites standardized to weight and time (bites * kg / hour)
-->
# Load, organize & select data
```{r}

ruv.raw <- read_excel("RUV bites_Herbivory browsing.xlsx")
colnames(ruv.raw)[which(names(ruv.raw) == "Object")] <- "Macroalgae"
ruv.raw$Macroalgae <- factor(ruv.raw$Macroalgae)
ruv.raw$Species <- factor(ruv.raw$Species)

# Data frame for Table (also split per Location)
ruv.0 <- data_summary(ruv.raw, varname = "smsBites",
                        groupnames = c("Location", "Species", "Macroalgae"))
ruv.0 <- subset(ruv.0, sum > 0)

# Data for Figure (pooled across Locations)
ruv.1 <- data_summary(ruv.raw, varname = "smsBites",
                        groupnames = c("Genus", "Species", "Macroalgae"))
ruv.1 <- subset(ruv.1, sum > 0)

colnames(ruv.1)[5] <- "smsBites"
ruv.1 <- ruv.1[c(2,3,5)]

# Add totals per species, so bar graph can be sorted from max to min
ruv.max <- ruv.1  %>%  
  group_by(Species) %>% 
  dplyr::summarise(Bites_max = sum(smsBites, na.rm = TRUE))

# Create category Other, for those species having relatively few Bites
Total <- sum(ruv.max$Bites_max)
ruv.max$Bites_pct <- ruv.max$Bites_max / Total * 100 # Express bites as percentages of total Bites

# Join dataframes
ruv.1 <- plyr::join(ruv.1, ruv.max, by = "Species")

# Change order of Macroalgae
ruv.1$Macroalgae <- factor(ruv.1$Macroalgae, ordered = T, levels = c("Sargassum", "Padina"))

# Order
ruv.1 <- ruv.1 %>%
  arrange(Bites_max) %>%               
  mutate(Species = fct_rev(factor(Species, unique(Species))))

```

# Summary table
```{r}

# Get totals per Location x Species x Macroalgae

ruv.table <- ruv.0  %>%  
  group_by(Species, Location, Macroalgae) %>% 
  dplyr::summarise(Bites = sum(mean, na.rm = TRUE))

# Make Macroalgae complete
ruv.table <- spread(ruv.table, key = Macroalgae, value = Bites)
ruv.table <- gather(ruv.table, Macroalgae, Bites, "Sargassum":"Padina") 

# Make Species complete
ruv.table <- spread(ruv.table, key = Species, value = Bites)
ruv.table <- gather(ruv.table, Species, Bites, 3:ncol(ruv.table))

# Reorder dataframe by max Bites per Species
ruv.table <- ruv.table %>%
  dplyr::arrange(sum(Bites)) %>%               
  dplyr::mutate(Species = factor(Species, unique(Species)))

# Set NAs (added for missing values) to 0
ruv.table$Bites <- as.numeric(ruv.table$Bites)
#ruv.table[is.na(ruv.table)] <- 0

# Organize data
ruv.table[with(ruv.table, order(Macroalgae, Location, Species)),]
ruv.table <- ruv.table[,c(3,1,2,4)]
ruv.table$Bites <- ceiling(ruv.table$Bites)

# Add Total sum colum
ruv.table <- spread(ruv.table, key = Macroalgae, value = Bites)
ruv.table$Sum <- rowSums(ruv.table[,c("Sargassum", "Padina")], na.rm=TRUE)

# Keep only first value of outer grouping column
ruv.table = ruv.table %>%
  group_by(Species) %>%
  mutate(count=1:n()) %>%
  ungroup %>%
  mutate(Species = ifelse(count==1, as.character(Species), NA)) %>%
  select(-count)

# Create table (can be copied into Word doc)
htmlTable(ruv.table, rnames = FALSE, align = "ll|rrr", align.header = "llrrr",
          col.rgroup = rep(c("none", "gray93"), each = as.numeric(length(unique(na.omit(ruv.table$Location))))),
          css.cell = c("padding-left: 0em", "padding-left: 1em", 
                       "padding-left: 4em", "padding-left: 4em", "padding-left: 2em" ))

# create new word document
new.word.doc=function(){
  my.doc=read_docx()
  return(my.doc)
}

# add an empty line
add.empty.line=function(doc){
  body_add_par(doc, " ")
  return("empty line added")
}

# add a data frame as a table
add.table=function(doc, tbl, col.keys=NULL, col.digits=NULL){
  # create basic flextable
  f.table=qflextable(tbl)
  
  # set table borders
  f.table=border_inner_h(f.table, part="header", border=fp_border(color="black", width = 1))
  #f.table=border_inner_v(f.table, part="all", border=fp_border(color="black", width = 1))
  
  # set fonts
  f.table=flextable::font(f.table,  fontname = "Times", part = "all")
  # also set the table's header font as bold
  f.table=bold(f.table, part = "header")
  
  # add the table to the document
  flextable::body_add_flextable(doc, 
                                value = f.table, 
                                align = "left" )
  return("table added")
}

# create a new document object
doc=new.word.doc()
add.table(doc, ruv.table)

# generate the Word document using the print function
print(doc, target="RUV_RUV by Location x Species.docx")
```

# Plotting
```{r}

ggplot(ruv.1, aes(fill = Macroalgae, y = smsBites, x = reorder(Species, -Bites_max))) + 
  geom_bar(position="stack", stat="identity")+
  scale_fill_manual(values = c("#323232", "#999999"))+
  scale_y_continuous(breaks = c(0, 10, 20), label = waiver (), limits = c (0, 25))+
  labs(x = "Species", y = expression(paste("Recorded bites (kg ", h^-1,")")))+
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color = "black", size = 14, vjust = 6, hjust = 0.5),
    axis.text.x = element_text(color="black", size = 12, face = "bold.italic", angle = -45,  hjust=0, vjust = 1),
    axis.title.y = element_text(color = "black",  size = 14, vjust = 4),
    axis.text.y = element_text(colour = "black", size = 12, vjust=0.5, face = "bold"),
    legend.position = "top",
    legend.box.margin = margin(0, 0, -5, 0),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 14, face = "bold.italic"),
    plot.margin = margin(t = 10, r = 55,  b = 0,  l = 20),
    panel.background = element_rect(fill = "#FCFCFC"),
    plot.background = element_rect(fill = "#FFFFFF"),
    panel.grid.major = element_line(colour = "#797979", size = 0.3)
  )
ggsave("RUV_RUV (Species X Macroalgae).tiff", width = 23, height = 13, units = "cm", dpi=1200, compression = "lzw")
```

# Save summary data to Excel for correlations for Grazing project
```{r corexcel}

RUV_Bites_Browsing <- data_summary(ruv.table, varname = "Sum", groupnames = c("Location"))
RUV_Bites_Browsing <- select(RUV_Bites_Browsing, c('Location', 'sum')) 
names(RUV_Bites_Browsing) <- c("Location", "BrowsingBites_kg.h")
write_xlsx(RUV_Bites_Browsing, "Correlations_RUVBrowsingBites.xlsx")

```

